import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/states/auth-context";
import { ProductContextProvider } from "@/states/product-context";
import { UserContextProvider } from "@/states/user-context";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import OneSignalWrapper from "./onesignal-wrapper";
import { SendTopupContextProvider } from "@/states/send-topup-context";
import { TopupRequestContextProvider } from "@/states/request-topup-context";
import { Toaster } from "@/components/ui/sonner";
import { HistoryContextProvider } from "@/states/history-context";

// const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${cn("font-sans")} bg-[#F9F9F9]`}>
        {/* <body className={`${inter.className} bg-[#DDE1E9]`}> */}
        <AuthContextProvider>
          <UserContextProvider>
            <ProductContextProvider>
              <SendTopupContextProvider>
                <TopupRequestContextProvider>
                  <HistoryContextProvider>
                    <OneSignalWrapper>{children}</OneSignalWrapper>
                  </HistoryContextProvider>
                </TopupRequestContextProvider>
              </SendTopupContextProvider>
            </ProductContextProvider>
          </UserContextProvider>
        </AuthContextProvider>

        <Toaster />
      </body>
    </html>
  );
}
